name: CI/CD Pipeline for ML project

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mirali818/flask-docker-app:latest

      # SSH into EC2 and deploy
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull mirali818/flask-docker-app:latest
            sudo docker stop flask-docker-app || true
            sudo docker rm flask-docker-app || true
            sudo docker run -d --name flask-docker-app -p 8080:8080 mirali818/flask-docker-app:latest